#ifndef EZFLAGS_H
#define EZFLAGS_H

#include <stdbool.h>
#include <stddef.h>
#include <unistd.h>

/*========================
 * Typedef
 * ======================== */

typedef struct s_flag
{
    char short_name;
    char *long_name;

    size_t min_args;
    long max_args;
    char **args;

    bool glued_arg;
    bool required;
    bool found;

    char *description;
    char *help_category;
    char **help_args;
} flag_t;

typedef enum e_status
{
    SUCCESS,

    // internal
    NOT_A_FLAG,
    NO_MORE_FLAG,

    // returnable
    MISSING_FLAG,
    FLAG_NOT_FOUND,
    FLAG_GROUP_NOT_FOUND,
    FLAG_GROUP_INVALID_ARGUMENT,
    REPTITIVE_FLAG,
    FLAG_ARGUMENT_NOT_FOUND,
    CANNOT_BE_GLUED,
    IMPOSSIBLE_FLAG,
    SYSTEM_ERROR,
    ERROR,

} ezflag_status;

/*========================
 * Define
 * ======================== */

#define EZ_HELP_ARGS(...)                                                     \
    (char *[]) { __VA_ARGS__, NULL }

#define EZ_FLAG_BOOL(sh, lg, desc, cat)                                       \
    { .short_name = sh,                                                       \
      .long_name = lg,                                                        \
      .description = desc,                                                    \
      .min_args = 0,                                                          \
      .max_args = 0,                                                          \
      .help_args = NULL,                                                      \
      .help_category = cat,                                                   \
      .glued_arg = false,                                                     \
      .required = false }

#define EZ_FLAG_OPT(sh, lg, req, desc, cat, arg_t)                            \
    { .short_name = sh,                                                       \
      .long_name = lg,                                                        \
      .description = desc,                                                    \
      .min_args = 1,                                                          \
      .max_args = 1,                                                          \
      .help_args = EZ_HELP_ARGS (arg_t),                                      \
      .help_category = cat,                                                   \
      .glued_arg = true,                                                      \
      .required = req }

#define EZ_FLAG_FULL(sh, lg, mini, maxi, glued, req, desc, cat, h_args)       \
    { .short_name = sh,                                                       \
      .long_name = lg,                                                        \
      .description = desc,                                                    \
      .min_args = mini,                                                       \
      .max_args = maxi,                                                       \
      .help_args = h_args,                                                    \
      .help_category = cat,                                                   \
      .glued_arg = glued,                                                     \
      .required = req }

/*========================
 * Public functions
 * ======================== */

/**
 * @brief Parse all argv and help you to get all flags and thair params
 *
 * @param flags flags to parse (argv + 1)
 * @param flag_array array that contain all the option define with opt_t type
 * (need a sentinelle)
 * @param still_argv pointer to a variable that will be allocated to store all
 * argv that are not specified flags
 * @return -1 in error case | number of flags not found | or 0 in total
 * success
 */
ezflag_status ezflags (char **args, flag_t flag_array[], char **still_argv[]);

/**
 * @brief Print in the standard input the --help based on the given flag list
 *
 * @param flag_array the flag list defined by the user
 */
void print_help (flag_t flag_array[]);

/*========================
 * Public helper functions
 * ======================== */

/**
 * @brief print a flag with a good format
 *
 * @param flag flag to print
 */
void print_flag (flag_t flag);

/**
 * @brief Print all the result of the parser
 *
 * @param flags flag array to print
 * @param still_argv array generated by ezflags
 */
void print_ezflags_result (flag_t flags[], char **still_argv);

#endif // EZFLAGS_H
